# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_stitching_arm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.visual = interface(self.centralwidget)
        self.visual.setGeometry(QtCore.QRect(29, 20, 671, 461))
        self.visual.setObjectName("visual")
        self.Homing = QtWidgets.QPushButton(self.centralwidget)
        self.Homing.setGeometry(QtCore.QRect(23, 500, 80, 21))
        self.Homing.setObjectName("Homing")
        self.coordlist = QtWidgets.QListWidget(self.centralwidget)
        self.coordlist.setGeometry(QtCore.QRect(443, 520, 231, 131))
        self.coordlist.setObjectName("coordlist")
        self.xcoord = QtWidgets.QLineEdit(self.centralwidget)
        self.xcoord.setGeometry(QtCore.QRect(23, 540, 81, 28))
        self.xcoord.setObjectName("xcoord")
        self.Submit = QtWidgets.QPushButton(self.centralwidget)
        self.Submit.setGeometry(QtCore.QRect(253, 580, 91, 28))
        self.Submit.setObjectName("Submit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(113, 540, 16, 31))
        self.label.setObjectName("label")
        self.ycoord = QtWidgets.QLineEdit(self.centralwidget)
        self.ycoord.setGeometry(QtCore.QRect(143, 540, 81, 28))
        self.ycoord.setObjectName("ycoord")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(233, 540, 16, 31))
        self.label_2.setObjectName("label_2")
        self.zcoord = QtWidgets.QLineEdit(self.centralwidget)
        self.zcoord.setGeometry(QtCore.QRect(253, 540, 81, 28))
        self.zcoord.setObjectName("zcoord")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(343, 540, 16, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 490, 221, 31))
        self.label_4.setObjectName("label_4")
        self.aabs = QtWidgets.QLineEdit(self.centralwidget)
        self.aabs.setGeometry(QtCore.QRect(720, 70, 81, 28))
        self.aabs.setObjectName("aabs")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(810, 70, 16, 31))
        self.label_5.setObjectName("label_5")
        self.babs = QtWidgets.QLineEdit(self.centralwidget)
        self.babs.setGeometry(QtCore.QRect(720, 110, 81, 28))
        self.babs.setObjectName("babs")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(810, 110, 16, 31))
        self.label_6.setObjectName("label_6")
        self.cabs = QtWidgets.QLineEdit(self.centralwidget)
        self.cabs.setGeometry(QtCore.QRect(720, 150, 81, 28))
        self.cabs.setObjectName("cabs")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(810, 150, 16, 31))
        self.label_7.setObjectName("label_7")
        self.dabs = QtWidgets.QLineEdit(self.centralwidget)
        self.dabs.setGeometry(QtCore.QRect(720, 190, 81, 28))
        self.dabs.setObjectName("dabs")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(810, 190, 16, 31))
        self.label_8.setObjectName("label_8")
        self.eabs = QtWidgets.QLineEdit(self.centralwidget)
        self.eabs.setGeometry(QtCore.QRect(720, 230, 81, 28))
        self.eabs.setObjectName("eabs")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(810, 230, 16, 31))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(710, 30, 101, 31))
        self.label_11.setObjectName("label_11")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(720, 270, 101, 51))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.aabs.setText(_translate("Mainwidow","0"))
        self.babs.setText(_translate("Mainwidow","0"))
        self.cabs.setText(_translate("Mainwidow","0"))
        self.dabs.setText(_translate("Mainwidow","0"))
        self.eabs.setText(_translate("Mainwidow","0"))
        self.xcoord.setText(_translate("Mainwidow","0"))
        self.ycoord.setText(_translate("Mainwidow","0"))
        self.zcoord.setText(_translate("Mainwidow","0"))
        self.Homing.setText(_translate("MainWindow", "Home"))
        self.Submit.setText(_translate("MainWindow", "Submit"))
        self.label.setText(_translate("MainWindow", "X"))
        self.label_2.setText(_translate("MainWindow", "Y"))
        self.label_3.setText(_translate("MainWindow", "Z"))
        self.label_4.setText(_translate("MainWindow", "List of coordinates"))
        self.label_5.setText(_translate("MainWindow", "A"))
        self.label_6.setText(_translate("MainWindow", "B"))
        self.label_7.setText(_translate("MainWindow", "C"))
        self.label_8.setText(_translate("MainWindow", "D"))
        self.label_9.setText(_translate("MainWindow", "E"))
        self.label_11.setText(_translate("MainWindow", "Absolute values"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Press ENTER </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">when done</p></body></html>"))
from interface import interface
#from App_space_mapping import visual_pointcloud